services:
  - type: web
    name: gerenciador-pacientes-odontologicos
    runtime: node
    plan: free
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
